
const BASE_W=1600,BASE_H=900;
function fit(){const s=Math.min(innerWidth/BASE_W,innerHeight/BASE_H);document.getElementById('fit').style.transform=`translate(-50%,-50%) scale(${s})`}
addEventListener('resize',fit);fit();
const app=document.getElementById('app');
const STORAGE_KEY='wow_beginner_unit8a_redesign_v2';
const SECTION_BY_SCREEN={1:'lexicon',2:'signs',3:'barrier',4:'builder',5:'sound',6:'places',7:'driving',8:'city'};
const SECTIONS=['lexicon','signs','barrier','builder','sound','places','driving','city'];
const LABELS={lexicon:'Road Words',signs:'Sign Decoder',barrier:'Open or Closed?',builder:'Road Builder',sound:'Sound Traffic Lights',places:'Four Stops',driving:'Driving Test',city:'City Permit Map'};
const data={
 lexicon:[
  {pairs:[['park','парковаться'],['pay by credit card','платить банковской картой'],['take photos','фотографировать'],['use the internet','пользоваться интернетом'],['drive fast','ехать быстро']]},
  {pairs:[['use your mobile phone','пользоваться телефоном'],['have a coffee','выпить кофе'],['play football','играть в футбол'],['change money','менять деньги'],['swim','плавать']]}
 ],
 signs:[
  {icon:'🏊',sign:'NO SWIMMING',a:'swim',o:['swim','drive fast','have a coffee']},
  {icon:'💳',sign:'CARD PAYMENT',a:'pay by credit card',o:['change money','pay by credit card','park']},
  {icon:'📵',sign:'PHONES OFF',a:'use your mobile phone',o:['take photos','use the internet','use your mobile phone']},
  {icon:'🅿️',sign:'PARKING',a:'park',o:['park','play football','swim']},
  {icon:'☕',sign:'CAFÉ',a:'have a coffee',o:['have a coffee','change money','drive fast']},
  {icon:'📶',sign:'FREE WI-FI',a:'use the internet',o:['use the internet','take photos','park']},
  {icon:'📷',sign:'NO PHOTOS',a:'take photos',o:['play football','take photos','have a coffee']},
  {icon:'⚽',sign:'NO BALL GAMES',a:'play football',o:['play football','swim','use the internet']},
  {icon:'💱',sign:'EXCHANGE',a:'change money',o:['change money','pay by credit card','use your mobile phone']},
  {icon:'🏫',sign:'SCHOOL ZONE',a:'drive fast',o:['drive fast','park','take photos']}
 ],
 barrier:[
  {scene:'There is a blue P sign next to the hotel.',allow:true,audio:'You can park here.'},
  {scene:'There is a No Parking sign by the school gate.',allow:false,audio:'You can’t park here.'},
  {scene:'The café has a card terminal.',allow:true,audio:'You can pay by credit card here.'},
  {scene:'The museum has a No Photos sign.',allow:false,audio:'You can’t take photos here.'},
  {scene:'The airport lounge has free wi-fi.',allow:true,audio:'You can use the internet here.'},
  {scene:'The sign says Phones Off.',allow:false,audio:'You can’t use your mobile phone here.'},
  {scene:'There is a school crossing ahead.',allow:false,audio:'You can’t drive fast here.'}
 ],
 builder:[
  {cue:'Собери: Здесь можно парковаться.',tokens:['You','can','park','here.'],audio:'You can park here.'},
  {cue:'Собери: Здесь нельзя фотографировать.',tokens:['You','can’t','take','photos','here.'],audio:'You can’t take photos here.'},
  {cue:'Собери: Можно заплатить банковской картой?',tokens:['Can','I','pay','by','credit','card?'],audio:'Can I pay by credit card?'},
  {cue:'Собери: Где можно обменять деньги?',tokens:['Where','can','I','change','money?'],audio:'Where can I change money?'},
  {cue:'Собери: Мы можем встретиться в десять.',tokens:['We','can','meet','at','ten.'],audio:'We can meet at ten.'},
  {cue:'Собери: Ты не можешь быстро ехать здесь.',tokens:['You','can’t','drive','fast','here.'],audio:'You can’t drive fast here.'}
 ],
 sound:[
  {audio:'We can park here.',a:'can',note:'Positive can is usually short and weak: /kən/.'},
  {audio:'I can’t help you.',a:'can’t',note:'British can’t is long and stressed: /kɑːnt/.'},
  {audio:'You can’t sit here.',a:'can’t',note:'Listen for the long stressed can’t.'},
  {audio:'Max can go with me.',a:'can',note:'Positive can is short and unstressed.'},
  {audio:'Can we swim here?',a:'can',note:'In questions can may be clearer, but it is still can, not can’t.'},
  {audio:'You can’t listen to music here.',a:'can’t',note:'The negative is stressed so the restriction is clear.'}
 ],
 places:{
  scripts:[
   {place:'train',icon:'🚆',lines:[{speaker:'Mia',text:'Excuse me, can I sit here?'},{speaker:'Leo',text:'Yes, I think it’s free.'},{speaker:'Mia',text:'Thanks.'}]},
   {place:'shop',icon:'🛍️',lines:[{speaker:'Shop assistant',text:'Can I help you?'},{speaker:'Nina',text:'Do you have this T-shirt in large?'},{speaker:'Shop assistant',text:'Sorry, we only have small and medium. I can phone another store.'}]},
   {place:'restaurant',icon:'🍽️',lines:[{speaker:'Waiter',text:'Are you ready to order?'},{speaker:'Eva',text:'Yes. Can I have the burger, but with salad, not chips?'},{speaker:'Waiter',text:'Yes, that’s fine.'}]},
   {place:'street',icon:'🎤',lines:[{speaker:'Local',text:'Hey! You can’t sing here.'},{speaker:'Sam',text:'Why not?'},{speaker:'Local',text:'Because you need a permit.'}]}
  ]
 },
 driving:{
  lines:[
   {speaker:'Examiner',text:'Good morning, Ms Jones.'},{speaker:'Anna',text:'Good morning. I’m very nervous.'},{speaker:'Examiner',text:'Can you start the car, please?'},{speaker:'Examiner',text:'OK. Turn right. Right, not left.'},{speaker:'Anna',text:'Sorry!'},{speaker:'Examiner',text:'The traffic lights are red! Stop!'},{speaker:'Examiner',text:'OK, can you park the car, please?'},{speaker:'Anna',text:'Can I park here?'},{speaker:'Examiner',text:'No, you can’t. Look, it’s no parking. Park over there.'},{speaker:'Anna',text:'Sorry. I’m very nervous.'}
  ],
  qs:[
   {q:'What does Anna do first?',a:'Start the car',o:['Start the car','Park the car','Turn left']},
   {q:'Which way should Anna turn?',a:'Right',o:['Left','Right','Straight on']},
   {q:'What should Anna do at the red traffic lights?',a:'Stop',o:['Drive fast','Stop','Park']},
   {q:'Can Anna park at the first place?',a:'No, she can’t.',o:['Yes, she can.','No, she can’t.','Only for five minutes.']},
   {q:'How does Anna feel?',a:'Nervous',o:['Nervous','Angry','Happy']}
  ]
 },
 city:{
  targets:[['pool','Swimming pool','🏊'],['cafe','Café','☕'],['museum','Museum','🏛️'],['park','Car park','🅿️'],['exchange','Exchange','💱'],['school','School zone','🏫']],
  items:[
   {q:'Where can you swim?',target:'pool',audio:'You can swim at the swimming pool.'},
   {q:'Where can you have a coffee?',target:'cafe',audio:'You can have a coffee at the café.'},
   {q:'Where can’t you take photos?',target:'museum',audio:'You can’t take photos in the museum.'},
   {q:'Where can you park?',target:'park',audio:'You can park in the car park.'},
   {q:'Where can you change money?',target:'exchange',audio:'You can change money at the exchange.'},
   {q:'Where can’t you drive fast?',target:'school',audio:'You can’t drive fast by the school.'}
  ]
 }
};
const MAX={lexicon:data.lexicon.length,signs:data.signs.length,barrier:data.barrier.length,builder:data.builder.length,sound:data.sound.length,places:data.places.scripts.length,driving:data.driving.qs.length,city:data.city.items.length};
const fresh=()=>({screen:0,idx:{lexicon:0,signs:0,barrier:0,builder:0,sound:0,places:0,driving:0,city:0},answers:{lexicon:{},signs:{},barrier:{},builder:{},sound:{},places:{},driving:{},city:{}},builderChosen:[],rhythmSelected:[],match:{left:null,right:null,matched:[]}});
let state=fresh();try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));if(s&&s.answers)state={...fresh(),...s,idx:{...fresh().idx,...(s.idx||{})},answers:{...fresh().answers,...(s.answers||{})},match:{...fresh().match,...(s.match||{})}}}catch(e){} state.screen=0;
try{const p=new URLSearchParams(location.search);if(p.has('screen')){const sc=+p.get('screen');if(!Number.isNaN(sc))state.screen=Math.max(0,Math.min(9,sc));}const sec=SECTION_BY_SCREEN[state.screen];if(sec&&p.has('idx')){const i=+p.get('idx');if(!Number.isNaN(i))state.idx[sec]=Math.max(0,Math.min(MAX[sec]-1,i));}}catch(e){}
let devMode=false;
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function esc(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function solved(sec,i){return !!state.answers[sec]?.[i]?.solved}
function score(sec){return Object.values(state.answers[sec]||{}).filter(x=>x.firstCorrect).length}
function recordAttempt(sec,i,ok){let a=state.answers[sec][i];if(!a)a=state.answers[sec][i]={attempts:0,firstCorrect:null,solved:false};a.attempts++;if(a.firstCorrect===null)a.firstCorrect=ok;if(ok)a.solved=true;save()}
function ordered(sec,idx,arr){const n=(idx+sec.length)%arr.length;return arr.slice(n).concat(arr.slice(0,n))}
function shuffledIndices(key,n){const a=Array.from({length:n},(_,i)=>i);let seed=2166136261;for(const ch of String(key)){seed^=ch.charCodeAt(0);seed=Math.imul(seed,16777619)}for(let i=n-1;i>0;i--){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const j=seed%(i+1);[a[i],a[j]]=[a[j],a[i]]}if(n>2&&a.every((v,i)=>v===i))a.push(a.shift());return a}
const PHRASE_ICONS={park:'🅿️','pay by credit card':'💳','take photos':'📷','use the internet':'📶','drive fast':'🚗','use your mobile phone':'📱','have a coffee':'☕','play football':'⚽','change money':'💱',swim:'🏊'};
function phraseIcon(text){return PHRASE_ICONS[text]||'📍'}
function changeTask(d){const s=SECTION_BY_SCREEN[state.screen];if(!s)return;const n=Math.max(0,Math.min(MAX[s]-1,state.idx[s]+d));if(n!==state.idx[s]){state.idx[s]=n;state.builderChosen=[];state.match={left:null,right:null,matched:[]};save();render()}}
function changeBlock(d){const n=Math.max(0,Math.min(9,state.screen+d));if(n!==state.screen){state.screen=n;state.builderChosen=[];state.match={left:null,right:null,matched:[]};save();render()}}
addEventListener('keydown',e=>{if(e.ctrlKey&&e.altKey&&e.key.toLowerCase()==='d'){e.preventDefault();devMode=!devMode;render()}if(e.altKey&&e.shiftKey&&e.key==='ArrowRight'){e.preventDefault();changeTask(1)}if(e.altKey&&e.shiftKey&&e.key==='ArrowLeft'){e.preventDefault();changeTask(-1)}if(e.altKey&&e.ctrlKey&&e.key==='ArrowRight'){e.preventDefault();changeBlock(1)}if(e.altKey&&e.ctrlKey&&e.key==='ArrowLeft'){e.preventDefault();changeBlock(-1)}});
function header(){return `<div class="header"><div class="brandCopy"><div class="brandName">WOW SCHOOL</div><div class="brandMeta">online english school · wow-school.ru</div><div class="brandModule">Beginner · Unit 8A · Can I park here?</div></div><div class="unitBadge" id="devToggle"><span>English File Beginner</span><strong>Unit 8A</strong></div></div>`}
function devBar(){if(!devMode)return '';const s=SECTION_BY_SCREEN[state.screen]||'home';return `<div class="devBar"><strong>DEV</strong><span>${s}</span><button class="devBtn" id="db1">◀ block</button><button class="devBtn" id="db2">block ▶</button><button class="devBtn" id="dt1">◀ task</button><button class="devBtn" id="dt2">task ▶</button></div>`}
function shell(inner){return `${header()}${devBar()}<section class="shell routeShell"><div class="content">${inner}</div></section>`}
function progress(n){return `<div class="progressBox routeProgress"><strong>Блок ${n}/8</strong><div class="track"><i style="width:${n/8*100}%"><b></b></i></div></div>`}
function title(n,t,sub){return `<div class="titlebar"><div class="titlewrap"><h1><span class="n">${n}.</span> ${t}</h1><p>Beginner · Unit 8A · ${sub}</p></div>${progress(n)}</div>`}
function mini(sec,idx,total){return `<div class="internalProgress"><div class="miniDots">${Array.from({length:total},(_,i)=>`<i class="miniDot ${i<idx?'done':i===idx?'current':''}"></i>`).join('')}</div><div class="counter">Задание ${idx+1} из ${total}</div></div>`}
function feedback(k,t){return `<div class="feedbackBox ${k}">${t}</div>`}
function listHint(items){return `<ul class="hintList">${items.map(x=>`<li>${x}</li>`).join('')}</ul>`}
function transcript(lines){return `<div class="transcriptBox">${lines.map(x=>`<p><b>${esc(x.speaker)}:</b> ${esc(x.text)}</p>`).join('')}</div>`}
function helpers(list=[]){const h=list.map(d=>`<details class="helperDetails"><summary>${esc(d.title)}</summary><div class="helperBody">${d.html}</div></details>`).join('');return h?`<div class="visualHelpers">${h}</div>`:''}
let playToken=0;const ttsAudio=document.createElement('audio');ttsAudio.preload='auto';ttsAudio.setAttribute('playsinline','');ttsAudio.referrerPolicy='no-referrer';ttsAudio.style.display='none';document.body.appendChild(ttsAudio);
function urls(t){const q=encodeURIComponent(t.replace(/\s+/g,' ').trim());return [`https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&tl=en-GB&q=${q}`,`https://translate.google.co.uk/translate_tts?ie=UTF-8&client=tw-ob&tl=en-GB&q=${q}`,`https://translate.googleapis.com/translate_tts?ie=UTF-8&client=gtx&tl=en-GB&q=${q}`]}
function chunks(t,max=170){const c=t.replace(/\s+/g,' ').trim();if(c.length<=max)return[c];const a=[];let r=c;while(r){if(r.length<=max){a.push(r);break}let cut=r.lastIndexOf(' ',max);if(cut<max*.5)cut=max;a.push(r.slice(0,cut));r=r.slice(cut).trim()}return a}
function stopAudio(){playToken++;try{ttsAudio.pause();ttsAudio.removeAttribute('src');ttsAudio.load()}catch(e){}}
function playUrl(u,tok){return new Promise((res,rej)=>{if(tok!==playToken)return rej();let done=false;const finish=ok=>{if(done)return;done=true;ttsAudio.onended=ttsAudio.onerror=null;ok?res():rej()};ttsAudio.onended=()=>finish(true);ttsAudio.onerror=()=>finish(false);ttsAudio.src=u;ttsAudio.currentTime=0;const p=ttsAudio.play();if(p&&p.catch)p.catch(()=>finish(false))})}
async function playChunk(t,tok){let e;for(const u of urls(t)){try{await playUrl(u,tok);return}catch(err){e=err}}throw e||new Error('audio')}
async function playSequence(lines,btn,idle='▶ Прослушать'){if(btn?.classList.contains('busy')){stopAudio();btn.classList.remove('busy');btn.textContent=idle;return}stopAudio();const tok=++playToken;btn?.classList.add('busy');if(btn)btn.textContent='■ Стоп';try{for(const t of lines){if(tok!==playToken)return;await playChunk(t,tok)}if(tok===playToken){btn?.classList.remove('busy');if(btn)btn.textContent=idle}}catch(e){if(tok===playToken){btn?.classList.remove('busy');btn?.classList.add('error');if(btn)btn.textContent='Аудио недоступно';setTimeout(()=>{btn?.classList.remove('error');if(btn)btn.textContent=idle},2000)}}}
function playText(t,b,idle='▶ Прослушать'){return playSequence(chunks(t),b,idle)}
function playScript(lines,b,label='Диалог'){return playSequence(lines.flatMap(x=>chunks(x.text,115)),b,`▶ ${label}`)}
function audioBtn(id,label='Прослушать'){return `<button class="audioBtn" id="${id}">▶ ${label}</button><span class="audioMeta">British English · синтез речи</span>`}
function visualSlot(file,icon,badge,caption,alt){return `<div class="visualSlot"><img src="assets/images/${file}" alt="${esc(alt)}" onerror="this.style.display='none'"><div class="visualBadge">${esc(badge)}</div><div class="slotFallback"><div><div class="slotIcon">${icon}</div><strong>${esc(badge)}</strong><span>${esc(caption)}</span><small>изображение добавим после генерации</small></div></div></div>`}
function visualWithHelpers(v,h){return `<div class="visualWithHelpers"><div class="visualMain">${v}</div>${helpers(h)}</div>`}
function heroSlot(){return `<div class="heroSlot"><img src="assets/images/preview-unit8a.jpg" alt="Unit 8A preview" onerror="this.style.display='none'"><div class="slotFallback"><div><div class="slotIcon">🅿️</div><strong>Can I park here?</strong><span>Город · правила · can / can’t · полезные verb phrases</span><small>WOW SCHOOL</small></div></div></div>`}
function flash(){const e=document.createElement('div');e.className='successFlash';document.querySelector('.shell')?.appendChild(e);setTimeout(()=>e.remove(),380)}
function bindGlobal(){const t=document.getElementById('devToggle');if(t)t.ondblclick=()=>{devMode=!devMode;render()};const map={db1:()=>changeBlock(-1),db2:()=>changeBlock(1),dt1:()=>changeTask(-1),dt2:()=>changeTask(1)};for(const [id,fn] of Object.entries(map)){const b=document.getElementById(id);if(b)b.onclick=fn}}
function start(){app.innerHTML=shell(`<div class="heroStart"><div class="heroCopy"><div class="eyebrow">WOW SCHOOL · Interactive lesson module</div><h1>Can I park<br><span>here?</span></h1><p>Сначала вы познакомитесь с ключевыми словами темы, затем научитесь понимать городские знаки и уверенно использовать can / can’t в реальных ситуациях. Дальше — произношение, короткие диалоги, driving test и финальная городская карта.</p><div class="heroPills"><span>🔗 English ↔ Русский</span><span>🚦 City signs</span><span>🚧 Can / can’t</span><span>🎧 Pronunciation</span><span>🗺️ City Permit Map</span></div><div class="heroBtns"><button class="btn primary" id="startBtn">Начать →</button><button class="btn secondary" id="resetBtn">Сбросить прогресс</button></div></div><div class="heroVisual">${heroSlot()}<div class="roadBadge"><span>CITY ROUTE</span><b>8A</b></div></div></div>`);startBtn.onclick=()=>{state.screen=1;save();render()};resetBtn.onclick=()=>{state=fresh();save();render()};bindGlobal()}

function lexicon(){const sec='lexicon',idx=state.idx[sec],pairs=data.lexicon[idx].pairs,done=solved(sec,idx);if(!state.match||!Array.isArray(state.match.matched))state.match={left:null,right:null,matched:[]};const matched=state.match.matched;const left=pairs.map((p,i)=>({text:p[0],i}));const right=[...pairs.map((p,i)=>({text:p[1],i}))].sort((a,b)=>((a.i*3+idx)%5)-((b.i*3+idx)%5));app.innerHTML=shell(`${title(1,'Road Words','English ↔ Russian · vocabulary first')}<div class="blockBody"><div class="visualCard">${visualWithHelpers(visualSlot('block1-lexicon.jpg','🗺️','ROAD WORDS','Сначала познакомьтесь с ключевыми словами темы','modern city map, parking signs and useful urban actions'),[{title:'Как играть?',html:listHint(['Нажмите английское слово слева.','Затем найдите его перевод справа.','Верная пара мягко подсветится и останется отмеченной.'])}])}</div><div class="questionCard"><div class="kicker">Vocabulary route · round ${idx+1}</div><div class="prompt">Match the words.</div><div class="subprompt">Сопоставьте английские фразы с переводом. Эти слова будут встречаться дальше в модуле.</div><div class="matchBoard" id="matchBoard"><div class="matchCol left">${left.map(x=>`<button class="matchItem ${matched.includes(x.i)?'matched':''} ${state.match.left===x.i?'selected':''}" data-left="${x.i}" ${matched.includes(x.i)||done?'disabled':''}>${esc(x.text)}</button>`).join('')}</div><div class="matchCol right">${right.map(x=>`<button class="matchItem ${matched.includes(x.i)?'matched':''} ${state.match.right===x.i?'selected':''}" data-right="${x.i}" ${matched.includes(x.i)||done?'disabled':''}>${esc(x.text)}</button>`).join('')}</div></div><div class="statusWrap"><div id="fb">${done?feedback('good','Все пары найдены!'):feedback('neutral',`Найдено пар ${matched.length} из ${pairs.length}`)}</div>${mini(sec,idx,data.lexicon.length)}</div></div></div><div class="footerActions"><div class="leftActions">${audioBtn('lexAudio','Все слова')}</div><button class="nextBtn" id="next" ${done?'':'disabled'}>${idx===data.lexicon.length-1?'Следующий блок →':'Следующий набор →'}</button></div>`);
 function checkPair(){if(state.match.left===null||state.match.right===null)return;if(state.match.left===state.match.right){matched.push(state.match.left);state.match.left=state.match.right=null;const ok=matched.length===pairs.length;if(ok)recordAttempt(sec,idx,true);else save();render()}else{recordAttempt(sec,idx,false);document.getElementById('fb').innerHTML=feedback('bad','Эта пара не подходит. Попробуйте ещё раз.');state.match.left=state.match.right=null;save();setTimeout(render,260)}}
 document.querySelectorAll('[data-left]').forEach(b=>b.onclick=()=>{state.match.left=+b.dataset.left;save();checkPair();if(state.match.right===null)render()});document.querySelectorAll('[data-right]').forEach(b=>b.onclick=()=>{state.match.right=+b.dataset.right;save();checkPair();if(state.match.left===null)render()});
 lexAudio.onclick=function(){playSequence(pairs.flatMap(p=>chunks(p[0],80)),this,'▶ Все слова')};next.onclick=()=>{state.match={left:null,right:null,matched:[]};if(idx<data.lexicon.length-1){state.idx[sec]=idx+1;save();render()}else{state.screen=2;save();render()}};bindGlobal()}

function signs(){const sec='signs',idx=state.idx[sec],item=data.signs[idx],done=solved(sec,idx),opts=ordered(sec,idx,item.o);app.innerHTML=shell(`${title(2,'Sign Decoder','read the sign · choose the verb phrase')}<div class="blockBody"><div class="visualCard">${visualWithHelpers(visualSlot('block2-signs.jpg','🚦','SIGN DECODER','Городские знаки помогают понять правило без перевода','clean urban signs, parking, museum, school and public places'),[{title:'Подсказка',html:listHint(['Посмотрите на знак и ключевую картинку.','Вспомните слова из первого блока.','Выберите действие, которое связано с этим знаком.'])}])}</div><div class="questionCard"><div class="kicker">City sign ${String(idx+1).padStart(2,'0')}</div><div class="prompt">What does this sign relate to?</div><div class="signGrid"><button class="signCard" disabled><div class="signIcon">${item.icon}</div><strong>${esc(item.sign)}</strong></button>${opts.map(o=>`<button class="signCard ${done&&o===item.a?'correct':''}" data-sign="${esc(o)}" ${done?'disabled':''}><div class="signIcon">${done&&o===item.a?'✓':phraseIcon(o)}</div><strong>${esc(o)}</strong></button>`).join('')}</div><div class="statusWrap"><div id="fb">${done?feedback('good','Верно! Вы правильно прочитали знак.'):feedback('neutral','Выберите подходящее действие.')}</div>${mini(sec,idx,data.signs.length)}</div></div></div><div class="footerActions"><div class="leftActions">${audioBtn('signAudio','Слово')}</div><button class="nextBtn" id="next" ${done?'':'disabled'}>${idx===data.signs.length-1?'Следующий блок →':'Следующий знак →'}</button></div>`);signAudio.onclick=function(){playText(item.a,this,'▶ Слово')};document.querySelectorAll('[data-sign]').forEach(b=>b.onclick=()=>{if(done)return;const ok=b.dataset.sign===item.a;recordAttempt(sec,idx,ok);if(ok){b.classList.add('correct');document.querySelectorAll('[data-sign]').forEach(x=>x.disabled=true);fb.innerHTML=feedback('good','Верно!');next.disabled=false}else{b.classList.add('wrongFlash');fb.innerHTML=feedback('bad','Вспомните перевод из первого блока.');setTimeout(()=>b.classList.remove('wrongFlash'),350)}});next.onclick=()=>{if(idx<data.signs.length-1){state.idx[sec]=idx+1;save();render()}else{state.screen=3;save();render()}};bindGlobal()}

function barrier(){const sec='barrier',idx=state.idx[sec],item=data.barrier[idx],done=solved(sec,idx),entry=state.answers[sec][idx]||{};app.innerHTML=shell(`${title(3,'Open or Closed?','can / can’t · permission and restriction')}<div class="blockBody"><div class="visualCard">${visualWithHelpers(visualSlot('block3-barrier.jpg','🚧','BARRIER GATE','Разрешение открывает шлагбаум, запрет оставляет его закрытым','parking barrier and modern city entrance'),[{title:'Мини-правило',html:listHint(['can = можно / разрешено','can’t = нельзя / запрещено','После can / can’t используется глагол без to.'])}])}</div><div class="questionCard"><div class="kicker">Parking gate · situation ${idx+1}</div><div class="prompt">${esc(item.scene)}</div><div class="subprompt">Разрешено или запрещено?</div><div class="barrierScene"><div class="barrierRoad"><div class="barrierPost"></div><div class="barrierArm ${done&&item.allow?'open':'closed'}"></div><div class="barrierLabel">${done?(item.allow?'CAN ✓':'CAN’T ✕'):'CHOOSE'}</div></div></div><div class="choiceSplit"><button class="bigChoice can" id="canBtn" ${done?'disabled':''}>CAN · можно</button><button class="bigChoice cant" id="cantBtn" ${done?'disabled':''}>CAN’T · нельзя</button></div><div class="statusWrap"><div id="fb">${done?feedback('good',item.audio):feedback('neutral','Выберите can или can’t.')}</div>${mini(sec,idx,data.barrier.length)}</div></div></div><div class="footerActions"><div class="leftActions">${audioBtn('barAudio','Модель')}</div><button class="nextBtn" id="next" ${done?'':'disabled'}>${idx===data.barrier.length-1?'Следующий блок →':'Следующая ситуация →'}</button></div>`);function choose(v){if(done)return;const ok=v===item.allow;recordAttempt(sec,idx,ok);if(ok){flash();render();setTimeout(()=>playText(item.audio,null,''),120)}else{fb.innerHTML=feedback('bad','Посмотрите на ситуацию ещё раз.');}}canBtn.onclick=()=>choose(true);cantBtn.onclick=()=>choose(false);barAudio.onclick=function(){playText(item.audio,this,'▶ Модель')};next.onclick=()=>{if(idx<data.barrier.length-1){state.idx[sec]=idx+1;save();render()}else{state.screen=4;save();render()}};bindGlobal()}

function builder(){const sec='builder',idx=state.idx[sec],item=data.builder[idx],done=solved(sec,idx);if(!Array.isArray(state.builderChosen))state.builderChosen=[];const chosen=state.builderChosen,bankOrder=shuffledIndices(`builder-${idx}`,item.tokens.length),bank=bankOrder.map(i=>({t:item.tokens[i],i})).filter(x=>!chosen.includes(x.i));app.innerHTML=shell(`${title(4,'Road Builder','build the sentence on the road')}<div class="blockBody"><div class="visualCard">${visualWithHelpers(visualSlot('block4-builder.jpg','🧩','ROAD BUILDER','Соберите полезную фразу из дорожных плиток','learner with city map, parking receipt and phrase cards'),[{title:'Подсказка',html:listHint(['В вопросе can ставим в начало: Can I…?','В утверждении: You can / You can’t + verb.','Нажмите на слово в собранной строке, чтобы убрать его.'])}])}</div><div class="questionCard"><div class="kicker">Build the route</div><div class="prompt">Make the sentence.</div><div class="builderWrap"><div class="builderCue">${esc(item.cue)}</div><div class="roadSentence">${chosen.map(i=>`<button class="roadToken" data-remove="${i}">${esc(item.tokens[i])}</button>`).join('')}</div><div class="tokenBank">${bank.map(x=>`<button class="bankToken" data-add="${x.i}">${esc(x.t)}</button>`).join('')}</div><div class="builderActions"><button class="smallBtn" id="clear">Очистить</button><button class="smallBtn primary" id="check">Проверить</button></div></div><div class="statusWrap"><div id="fb">${done?feedback('good','Маршрут собран правильно.'):feedback('neutral','Соберите предложение по порядку.')}</div>${mini(sec,idx,data.builder.length)}</div></div></div><div class="footerActions"><div class="leftActions">${audioBtn('buildAudio','Модель')}</div><button class="nextBtn" id="next" ${done?'':'disabled'}>${idx===data.builder.length-1?'Следующий блок →':'Следующая фраза →'}</button></div>`);document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{state.builderChosen.push(+b.dataset.add);save();builder()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.builderChosen=state.builderChosen.filter(x=>x!==+b.dataset.remove);save();builder()});clear.onclick=()=>{state.builderChosen=[];save();builder()};check.onclick=()=>{const ok=chosen.length===item.tokens.length&&chosen.every((v,i)=>v===i);recordAttempt(sec,idx,ok);if(ok){fb.innerHTML=feedback('good','Верно!');next.disabled=false;playText(item.audio,null,'')}else fb.innerHTML=feedback('bad','Проверьте порядок слов.')};buildAudio.onclick=function(){playText(item.audio,this,'▶ Модель')};next.onclick=()=>{state.builderChosen=[];if(idx<data.builder.length-1){state.idx[sec]=idx+1;save();render()}else{state.screen=5;save();render()}};bindGlobal()}

function sound(){const sec='sound',idx=state.idx[sec],item=data.sound[idx],done=solved(sec,idx),entry=state.answers[sec][idx]||{};app.innerHTML=shell(`${title(5,'Sound Traffic Lights','hear can / can’t · British English')}<div class="blockBody"><div class="visualCard">${visualWithHelpers(visualSlot('block5-sound.jpg','🎧','SOUND TRAFFIC LIGHTS','Слушайте короткую фразу и отличайте can от can’t','headphones, urban study corner and traffic-light theme'),[{title:'Как услышать разницу?',html:listHint(['can в положительной фразе обычно короткое и слабое: /kən/.','can’t в British English длиннее и ударное: /kɑːnt/.','Сначала прослушайте, затем выберите нужный сигнал.'])}])}</div><div class="questionCard"><div class="kicker">Listen · signal ${idx+1}</div><div class="prompt">Do you hear can or can’t?</div><div class="soundPanel"><div class="trafficLight"><button class="light can ${done&&item.a==='can'?'on':''}" id="lightCan" ${done?'disabled':''}>CAN</button><button class="light cant ${done&&item.a==='can’t'?'on':''}" id="lightCant" ${done?'disabled':''}>CAN’T</button></div><div class="soundInfo"><h3>British English</h3><p>Сначала нажмите «Фразу», затем выберите сигнал.</p><div class="phonetic"><span>can /kən/</span><span>can’t /kɑːnt/</span></div>${done?`<p><b>${esc(item.audio)}</b></p><p>${esc(item.note)}</p>`:''}</div></div><div class="statusWrap"><div id="fb">${done?feedback('good','Верно! Разницу услышали.'):feedback('neutral','Прослушайте фразу и выберите can или can’t.')}</div>${mini(sec,idx,data.sound.length)}</div></div></div><div class="footerActions"><div class="leftActions">${audioBtn('soundAudio','Фразу')}</div><button class="nextBtn" id="next" ${done?'':'disabled'}>${idx===data.sound.length-1?'Следующий блок →':'Следующий сигнал →'}</button></div>`);soundAudio.onclick=function(){playText(item.audio,this,'▶ Фразу')};function choose(v){if(done)return;const ok=v===item.a;recordAttempt(sec,idx,ok);if(ok){flash();render()}else fb.innerHTML=feedback('bad','Послушайте ещё раз: can короткое, can’t длинное и ударное.')};lightCan.onclick=()=>choose('can');lightCant.onclick=()=>choose('can’t');next.onclick=()=>{if(idx<data.sound.length-1){state.idx[sec]=idx+1;save();render()}else{state.screen=6;save();render()}};bindGlobal()}

function places(){const sec='places',idx=state.idx[sec],script=data.places.scripts[idx],done=solved(sec,idx);const choices=[['train','🚆'],['shop','🛍️'],['restaurant','🍽️'],['street','🎤']];app.innerHTML=shell(`${title(6,'Four Stops','listen to a mini-dialogue · identify the place')}<div class="blockBody"><div class="visualCard">${visualWithHelpers(visualSlot('block6-places.jpg','📍','FOUR STOPS','Определите место по короткому диалогу','city route with train, shop, restaurant and street locations'),[{title:'Открыть текст диалога',html:transcript(script.lines)},{title:'Лёгкая подсказка',html:listHint(['Ищите слова, характерные для места.','sit here → train','T-shirt → shop','order / burger → restaurant','permit → street'])}])}</div><div class="questionCard"><div class="kicker">Route stop ${idx+1}</div><div class="prompt">Where are they?</div><div class="routeStops">${choices.map((x,i)=>`<div class="routeStop ${i<idx?'done':i===idx?'live':''}">${i+1}</div>`).join('')}</div><div class="placeCards">${choices.map(([p,ic])=>`<button class="placeCard ${done&&p===script.place?'correct':''}" data-place="${p}" ${done?'disabled':''}><span>${ic}</span><b>${p}</b></button>`).join('')}</div><div class="statusWrap"><div id="fb">${done?feedback('good',`Верно: ${script.place}.`):feedback('neutral','Прослушайте диалог и выберите место.')}</div>${mini(sec,idx,data.places.scripts.length)}</div></div></div><div class="footerActions"><div class="leftActions">${audioBtn('placeAudio','Диалог')}</div><button class="nextBtn" id="next" ${done?'':'disabled'}>${idx===data.places.scripts.length-1?'Следующий блок →':'Следующая остановка →'}</button></div>`);placeAudio.onclick=function(){playScript(script.lines,this,'Диалог')};document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>{if(done)return;const ok=b.dataset.place===script.place;recordAttempt(sec,idx,ok);if(ok){b.classList.add('correct');document.querySelectorAll('[data-place]').forEach(x=>x.disabled=true);fb.innerHTML=feedback('good',`Верно: ${script.place}.`);next.disabled=false}else{b.classList.add('wrongFlash');fb.innerHTML=feedback('bad','Не это место. Откройте текст, если нужно.');setTimeout(()=>b.classList.remove('wrongFlash'),350)}});next.onclick=()=>{if(idx<data.places.scripts.length-1){state.idx[sec]=idx+1;save();render()}else{state.screen=7;save();render()}};bindGlobal()}

function driving(){const sec='driving',idx=state.idx[sec],item=data.driving.qs[idx],done=solved(sec,idx),opts=ordered(sec,idx,item.o);app.innerHTML=shell(`${title(7,'Driving Test','follow Anna’s test step by step')}<div class="blockBody"><div class="visualCard"><div class="visualWithHelpers"><div class="visualMain"><div class="testPanel"><div class="testImage">${visualSlot('block7-driving.jpg','🚗','DRIVING TEST','Следите за испытанием Анны шаг за шагом','young learner driver with examiner at a driving test')}</div><div class="testText">${data.driving.lines.map(x=>`<p><b>${esc(x.speaker)}:</b> ${esc(x.text)}</p>`).join('')}</div></div></div>${helpers([{title:'Подсказка',html:listHint(['Читайте только нужную часть ситуации.','Знаки и команды экзаменатора дают ответ.','В аудио имена не произносятся — звучат только реплики.'])}])}</div></div><div class="questionCard"><div class="kicker">Test checkpoint ${idx+1}</div><div class="prompt">${esc(item.q)}</div><div class="checklist">${opts.map((o,i)=>`<button class="checkRow ${done&&o===item.a?'good':''}" data-drive="${esc(o)}" ${done?'disabled':''}><span>${i+1}</span><b>${esc(o)}</b></button>`).join('')}</div><div class="statusWrap"><div id="fb">${done?feedback('good','Верно! Этап теста пройден.'):feedback('neutral','Выберите правильный вариант.')}</div>${mini(sec,idx,data.driving.qs.length)}</div></div></div><div class="footerActions"><div class="leftActions">${audioBtn('driveAudio','Диалог')}</div><button class="nextBtn" id="next" ${done?'':'disabled'}>${idx===data.driving.qs.length-1?'Следующий блок →':'Следующий этап →'}</button></div>`);driveAudio.onclick=function(){playScript(data.driving.lines,this,'Диалог')};document.querySelectorAll('[data-drive]').forEach(b=>b.onclick=()=>{if(done)return;const ok=b.dataset.drive===item.a;recordAttempt(sec,idx,ok);if(ok){b.classList.add('good');document.querySelectorAll('[data-drive]').forEach(x=>x.disabled=true);fb.innerHTML=feedback('good','Верно!');next.disabled=false}else{b.classList.add('bad');fb.innerHTML=feedback('bad','Посмотрите на последовательность driving test ещё раз.');setTimeout(()=>b.classList.remove('bad'),350)}});next.onclick=()=>{if(idx<data.driving.qs.length-1){state.idx[sec]=idx+1;save();render()}else{state.screen=8;save();render()}};bindGlobal()}

function city(){const sec='city',idx=state.idx[sec],item=data.city.items[idx],done=solved(sec,idx),targets=data.city.targets;app.innerHTML=shell(`${title(8,'City Permit Map','signature block · use the vocabulary in a city')}<div class="blockBody"><div class="visualCard">${visualWithHelpers(visualSlot('block8-citymap.jpg','🗺️','CITY PERMIT MAP','Финальная практика: найдите нужное место на городской карте','premium urban map scene with parking, museum, café, pool and school zone'),[{title:'Как играть?',html:listHint(['Прочитайте или прослушайте вопрос.','Найдите нужное место на карте справа.','После правильного выбора прозвучит готовая модель с can / can’t.'])}])}</div><div class="questionCard"><div class="kicker">City route · stop ${idx+1}</div><div class="prompt">${esc(item.q)}</div><div class="subprompt">Выберите нужное место.</div><div class="cityMap"><div class="mapGrid">${targets.map(([id,label,ic])=>`<button class="mapPlace ${done&&id===item.target?'captured':''}" data-target="${id}" ${done?'disabled':''}><span>${ic}</span><b>${esc(label)}</b></button>`).join('')}</div></div><div class="routeRibbon">${data.city.items.map((_,i)=>`<i class="${i<idx?'done':i===idx?'live':''}"></i>`).join('')}</div><div class="statusWrap"><div id="fb">${done?feedback('good',item.audio):feedback('neutral','Найдите правильное место на карте.')}</div>${mini(sec,idx,data.city.items.length)}</div></div></div><div class="footerActions"><div class="leftActions">${audioBtn('cityAudio','Вопрос')}</div><button class="nextBtn" id="next" ${done?'':'disabled'}>${idx===data.city.items.length-1?'Результаты →':'Следующая точка →'}</button></div>`);cityAudio.onclick=function(){playText(item.q,this,'▶ Вопрос')};document.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>{if(done)return;const ok=b.dataset.target===item.target;recordAttempt(sec,idx,ok);if(ok){b.classList.add('captured');document.querySelectorAll('[data-target]').forEach(x=>x.disabled=true);fb.innerHTML=feedback('good',item.audio);next.disabled=false;flash();playText(item.audio,null,'')}else{b.classList.add('wrongFlash');fb.innerHTML=feedback('bad','Не эта точка. Вспомните значение ключевого глагола.');setTimeout(()=>b.classList.remove('wrongFlash'),350)}});next.onclick=()=>{if(idx<data.city.items.length-1){state.idx[sec]=idx+1;save();render()}else{state.screen=9;save();render()}};bindGlobal()}

function results(){const totalMax=SECTIONS.reduce((n,k)=>n+MAX[k],0),total=SECTIONS.reduce((n,k)=>n+score(k),0),pct=Math.round(total/totalMax*100),sorted=[...SECTIONS].sort((a,b)=>score(b)/MAX[b]-score(a)/MAX[a]),best=sorted[0],weak=sorted.at(-1);app.innerHTML=shell(`<div class="titlebar"><div class="titlewrap"><h1>Your <span class="n">Results</span></h1><p>Beginner · Unit 8A · Can I park here?</p></div><div class="progressBox"><strong>Готово</strong><div class="track"><i style="width:100%"></i></div></div></div><div class="results"><div class="ring" style="--pct:${pct}"><strong>${pct}%</strong><span>с первого раза</span></div><div><div class="resultList">${SECTIONS.map(k=>{const p=Math.round(score(k)/MAX[k]*100);return `<div class="resrow"><label>${LABELS[k]}</label><div class="resbar"><i style="width:${p}%"></i></div><b>${score(k)}/${MAX[k]}</b></div>`}).join('')}</div><div class="coach"><div><strong>Лучший участок</strong><p>${LABELS[best]} — здесь результат самый сильный.</p></div><div><strong>Полезно повторить</strong><p>${LABELS[weak]} — этот блок стоит пройти ещё раз.</p></div></div><div class="coach"><div><strong>Вы потренировали</strong><p>Ключевую лексику, can / can’t, городские знаки, аудирование, чтение и произношение.</p></div><div><strong>Финальная практика</strong><p>Скажите вслух: Can I park here? You can park here. You can’t park here.</p></div></div><div class="heroBtns"><button class="btn primary" id="retry">Пройти ещё раз</button><button class="btn secondary" id="home">На главную</button></div></div></div>`);retry.onclick=()=>{state=fresh();state.screen=1;save();render()};home.onclick=()=>{state.screen=0;save();render()};bindGlobal()}
let lastViewKey=null,lastScreen=null;
function decorateView(){
  const sec=SECTION_BY_SCREEN[state.screen];
  const idx=sec?state.idx[sec]:0;
  const key=`${state.screen}:${idx}`;
  const shellEl=document.querySelector('.routeShell');
  if(shellEl){
    const cls=lastScreen===null||lastScreen!==state.screen?'routeEnterBlock':(lastViewKey!==key?'routeEnterTask':'routeStay');
    shellEl.classList.add(cls);
  }
  lastViewKey=key;lastScreen=state.screen;
}
function render(){stopAudio();({0:start,1:lexicon,2:signs,3:barrier,4:builder,5:sound,6:places,7:driving,8:city,9:results}[state.screen]||start)();requestAnimationFrame(decorateView)}
render();
