const BASE_W=1600,BASE_H=900;
function fit(){const s=Math.min(innerWidth/BASE_W,innerHeight/BASE_H);document.getElementById('fit').style.transform=`translate(-50%,-50%) scale(${s})`}
addEventListener('resize',fit);fit();

const app=document.getElementById('app');
const STORAGE_KEY='wow_beginner_episode4_whats_the_date_v1';
const SECTION_BY_SCREEN={1:'months',2:'ordinals',3:'match',4:'calendar',5:'builder',6:'phone',7:'stamp',8:'save'};
const SECTIONS=['months','ordinals','match','calendar','builder','phone','stamp','save'];
const LABELS={months:'Month Flip',ordinals:'Ordinal Lift',match:'Date Match',calendar:'Calendar Tap',builder:'Sentence Builder',phone:'Phone English',stamp:'Date Stamp',save:'Save the Date'};

const MONTHS=['January','February','March','April','May','June','July','August','September','October','November','December'];
const MONTHS_RU=['январь','февраль','март','апрель','май','июнь','июль','август','сентябрь','октябрь','ноябрь','декабрь'];
const ORD_WORDS={1:'first',2:'second',3:'third',4:'fourth',5:'fifth',6:'sixth',7:'seventh',8:'eighth',9:'ninth',10:'tenth',11:'eleventh',12:'twelfth',13:'thirteenth',14:'fourteenth',15:'fifteenth',16:'sixteenth',17:'seventeenth',18:'eighteenth',19:'nineteenth',20:'twentieth',21:'twenty-first',22:'twenty-second',23:'twenty-third',24:'twenty-fourth',25:'twenty-fifth',26:'twenty-sixth',27:'twenty-seventh',28:'twenty-eighth',29:'twenty-ninth',30:'thirtieth',31:'thirty-first'};
function suffix(n){const v=n%100;if(v>=11&&v<=13)return 'th';return {1:'st',2:'nd',3:'rd'}[n%10]||'th'}
function datePhrase(day,month){return `the ${ORD_WORDS[day]} of ${month}`}

const data={
  months:[
    {ru:'январь',en:'January',num:1,o:['January','June','July','November']},
    {ru:'февраль',en:'February',num:2,o:['February','April','August','October']},
    {ru:'март',en:'March',num:3,o:['March','May','June','September']},
    {ru:'апрель',en:'April',num:4,o:['April','August','October','December']},
    {ru:'май',en:'May',num:5,o:['May','March','June','July']},
    {ru:'июнь',en:'June',num:6,o:['June','July','January','September']},
    {ru:'июль',en:'July',num:7,o:['July','June','January','February']},
    {ru:'август',en:'August',num:8,o:['August','April','October','December']},
    {ru:'сентябрь',en:'September',num:9,o:['September','November','December','February']},
    {ru:'октябрь',en:'October',num:10,o:['October','November','August','April']},
    {ru:'ноябрь',en:'November',num:11,o:['November','September','October','December']},
    {ru:'декабрь',en:'December',num:12,o:['December','November','September','February']}
  ],
  ordinals:[
    {n:1,a:'1st',word:'first',o:['1st','2nd','3rd','4th']},
    {n:2,a:'2nd',word:'second',o:['2nd','12th','20th','22nd']},
    {n:3,a:'3rd',word:'third',o:['3rd','13th','23rd','30th']},
    {n:8,a:'8th',word:'eighth',o:['8th','18th','28th','9th']},
    {n:12,a:'12th',word:'twelfth',o:['12th','20th','2nd','22nd']},
    {n:20,a:'20th',word:'twentieth',o:['20th','21st','12th','30th']},
    {n:23,a:'23rd',word:'twenty-third',o:['23rd','22nd','13th','30th']},
    {n:31,a:'31st',word:'thirty-first',o:['31st','30th','21st','13th']}
  ],
  match:[
    [
      {spoken:'the first of January',written:'1st January'},
      {spoken:'the fourteenth of February',written:'14th February'},
      {spoken:'the twenty-third of March',written:'23rd March'},
      {spoken:'the ninth of April',written:'9th April'}
    ],
    [
      {spoken:'the eleventh of May',written:'11th May'},
      {spoken:'the twentieth of August',written:'20th August'},
      {spoken:'the twenty-second of September',written:'22nd September'},
      {spoken:'the thirty-first of December',written:'31st December'}
    ]
  ],
  calendar:[
    {day:14,month:'February'},{day:8,month:'March'},{day:9,month:'April'},{day:11,month:'May'},
    {day:14,month:'June'},{day:18,month:'July'},{day:22,month:'September'},{day:31,month:'December'}
  ],
  builder:[
    {ru:'Какое сегодня число?',a:"What's the date today?",tokens:["What's",'the','date','today?']},
    {ru:'Сегодня первое апреля.',a:"It's the first of April.",tokens:["It's",'the','first','of','April.']},
    {ru:'Ты уверен / уверена?',a:'Are you sure?',tokens:['Are','you','sure?']},
    {ru:'Разве сегодня не второе?',a:"Isn't it the second?",tokens:["Isn't",'it','the','second?']},
    {ru:'Сегодня день рождения моего папы.',a:"It's my dad's birthday.",tokens:["It's",'my',"dad's",'birthday.']},
    {ru:'Когда у тебя день рождения?',a:"When's your birthday?",tokens:["When's",'your','birthday?']},
    {ru:'Позвони мне в понедельник.',a:'Call me on Monday.',tokens:['Call','me','on','Monday.']}
  ],
  phone:[
    {caller:'Leo',lines:[{name:'Anna',text:"Hi, Leo. What's the date today?"},{name:'Leo',text:"It's the twelfth of June."}],q:'What is the date?',a:'12th June',o:['12th June','20th June','2nd July']},
    {caller:'Mia',lines:[{name:'Tom',text:'Is your birthday on the first of July?'},{name:'Mia',text:"No, it's on the third."}],q:"When is Mia's birthday?",a:'3rd July',o:['1st July','3rd July','13th July']},
    {caller:'Eva',lines:[{name:'Ben',text:'Can you call me on Monday?'},{name:'Eva',text:'Of course.'}],q:'When should Eva call Ben?',a:'Monday',o:['Monday','Tuesday','Friday']},
    {caller:'Jack',lines:[{name:'Laura',text:'Are you free on the twenty-first of September?'},{name:'Jack',text:'Yes, I am.'}],q:'Which date do they mention?',a:'21st September',o:['12th September','21st September','22nd September']},
    {caller:'Sam',lines:[{name:'Amy',text:"My dad's birthday is on the ninth of April."},{name:'Sam',text:'Great. Thanks!'}],q:"Whose birthday is on 9th April?",a:"Amy's dad's",o:["Amy's dad's","Sam's","Amy's"]},
    {caller:'Emma',lines:[{name:'Noah',text:'Talk to you on Tuesday.'},{name:'Emma',text:'OK. Bye!'}],q:'Which day do they say?',a:'Tuesday',o:['Tuesday','Thursday','Sunday']}
  ],
  stamp:[
    {event:'Birthday dinner',cue:'the fifth of May',a:'5th May',o:['5th May','15th May','5th March'],audio:'the fifth of May'},
    {event:'Train ticket',cue:'22nd September',a:'the twenty-second of September',o:['the second of September','the twenty-second of September','the twentieth of September'],audio:'the twenty-second of September'},
    {event:'Family lunch',cue:'the third of June',a:'3rd June',o:['13th June','3rd June','30th June'],audio:'the third of June'},
    {event:'Appointment',cue:'11th November',a:'the eleventh of November',o:['the eleventh of November','the first of November','the twenty-first of November'],audio:'the eleventh of November'},
    {event:'Concert',cue:'the eighteenth of July',a:'18th July',o:['8th July','18th July','28th July'],audio:'the eighteenth of July'},
    {event:'Holiday',cue:'31st December',a:'the thirty-first of December',o:['the thirteenth of December','the thirty-first of December','the thirtieth of December'],audio:'the thirty-first of December'},
    {event:'Coffee with Mia',cue:'the ninth of April',a:'9th April',o:['9th April','19th April','9th August'],audio:'the ninth of April'},
    {event:'Museum day',cue:'20th August',a:'the twentieth of August',o:['the twelfth of August','the twentieth of August','the twenty-second of August'],audio:'the twentieth of August'}
  ],
  save:[
    {person:'Mia',text:'My birthday is on the seventeenth of July.',ru:'Мой день рождения — семнадцатого июля.',month:6,day:17},
    {person:'Leo',text:'The meeting is on the ninth of April.',ru:'Встреча — девятого апреля.',month:3,day:9},
    {person:'Anna',text:'Call me on the twenty-second of September.',ru:'Позвони мне двадцать второго сентября.',month:8,day:22},
    {person:'Ben',text:'The party is on the third of June.',ru:'Вечеринка — третьего июня.',month:5,day:3},
    {person:'Eva',text:'My holiday starts on the first of August.',ru:'Мой отпуск начинается первого августа.',month:7,day:1},
    {person:'Tom',text:'The dinner is on the thirty-first of December.',ru:'Ужин — тридцать первого декабря.',month:11,day:31}
  ]
};

const MAX={months:data.months.length,ordinals:data.ordinals.length,match:8,calendar:data.calendar.length,builder:data.builder.length,phone:data.phone.length,stamp:data.stamp.length,save:data.save.length};
function fresh(){return {screen:0,idx:{months:0,ordinals:0,calendar:0,builder:0,phone:0,stamp:0,save:0},answers:Object.fromEntries(SECTIONS.map(k=>[k,{}])),mistakes:{},matchRound:0,matchFound:{0:[],1:[]},matchLeft:null,builderChosen:[],picker:{}}}
let state=fresh();
try{const old=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(old)state={...fresh(),...old,idx:{...fresh().idx,...(old.idx||{})},answers:{...fresh().answers,...(old.answers||{})},matchFound:{0:[],1:[],...(old.matchFound||{})},picker:{...(old.picker||{})}}}catch(e){}
try{const p=new URLSearchParams(location.search);if(p.has('screen')){const s=+p.get('screen');if(!Number.isNaN(s))state.screen=Math.max(0,Math.min(9,s));}const sec=SECTION_BY_SCREEN[state.screen];if(sec&&p.has('idx')){const i=+p.get('idx');if(sec==='match'){state.matchRound=Math.max(0,Math.min(1,i));}else if(state.idx[sec]!==undefined&&!Number.isNaN(i)){state.idx[sec]=Math.max(0,Math.min(MAX[sec]-1,i));}}}catch(e){}
let devMode=false;
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function esc(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function solved(sec,i){return !!state.answers[sec]?.[i]?.solved}
function score(sec){return Object.values(state.answers[sec]||{}).filter(x=>x.firstCorrect).length}
function recordAttempt(sec,i,isCorrect){let a=state.answers[sec][i];if(!a){a={attempts:0,firstCorrect:null,solved:false};state.answers[sec][i]=a}a.attempts++;if(a.firstCorrect===null)a.firstCorrect=isCorrect;if(isCorrect)a.solved=true;state.mistakes[`${sec}:${i}`]=isCorrect?null:true;save()}
function rotateOptions(opts,seed){const n=opts.length,off=((seed*3+1)%n);return opts.slice(off).concat(opts.slice(0,off))}
function currentSection(){return SECTION_BY_SCREEN[state.screen]||null}
function currentTaskLabel(){const sec=currentSection();if(!sec)return 'Start';if(sec==='match')return `round ${state.matchRound+1}/2`;return `${(state.idx[sec]||0)+1}/${MAX[sec]}`}
function changeTask(dir){const sec=currentSection();if(!sec)return;if(sec==='match'){state.matchRound=Math.max(0,Math.min(1,state.matchRound+dir));state.matchLeft=null;save();render();return}if(!(sec in state.idx))return;const cur=state.idx[sec]||0,next=Math.max(0,Math.min(MAX[sec]-1,cur+dir));if(next!==cur){state.idx[sec]=next;state.builderChosen=[];save();render()}}
function changeBlock(dir){const next=Math.max(0,Math.min(9,(state.screen||0)+dir));if(next!==state.screen){state.screen=next;state.matchLeft=null;state.builderChosen=[];save();render()}}
addEventListener('keydown',e=>{if(e.ctrlKey&&e.altKey&&e.key.toLowerCase()==='d'){e.preventDefault();devMode=!devMode;render();return}if(e.altKey&&e.shiftKey&&e.key==='ArrowRight'){e.preventDefault();changeTask(1)}if(e.altKey&&e.shiftKey&&e.key==='ArrowLeft'){e.preventDefault();changeTask(-1)}if(e.altKey&&e.ctrlKey&&e.key==='ArrowRight'){e.preventDefault();changeBlock(1)}if(e.altKey&&e.ctrlKey&&e.key==='ArrowLeft'){e.preventDefault();changeBlock(-1)}});

function header(){return `<div class="noise"></div><div class="header"><div class="brandHeader"><div class="brandCopy"><div class="brandName">WOW SCHOOL</div><div class="brandMeta">online english school · wow-school.ru</div><div class="brandModule">Beginner · Episode 4 · Practical English · What's the date?</div></div></div><div class="unitBadge" id="devToggle"><span>English File Beginner</span><strong>Episode 4</strong></div></div>`}
function devBar(){if(!devMode)return '';return `<div class="devBar"><strong>DEV</strong><span>${currentSection()||'home'} · ${currentTaskLabel()}</span><button class="devBtn" id="devPrevBlock">◀ block</button><button class="devBtn" id="devNextBlock">block ▶</button><button class="devBtn" id="devPrevTask">◀ task</button><button class="devBtn" id="devNextTask">task ▶</button></div>`}
function shell(inner){return `${header()}${devBar()}<section class="shell dateShell"><div class="content">${inner}</div></section>`}
function progress(n){return `<div class="progressBox"><strong>Блок ${n}/8</strong><div class="track"><i style="width:${n/8*100}%"></i></div></div>`}
function title(n,t,sub){return `<div class="titlebar"><div class="titlewrap"><h1><span class="n">${n}.</span> ${t}</h1><p>${sub}</p></div>${progress(n)}</div>`}
function miniProgress(sec,idx,total){return `<div class="internalProgress"><div class="miniDots">${Array.from({length:total},(_,i)=>`<i class="miniDot ${i<idx?'done':i===idx?'current':''}"></i>`).join('')}</div><div class="counter">Задание ${Math.min(idx+1,total)} из ${total}</div></div>`}
function feedback(kind,text){return `<div class="feedbackBox ${kind}">${text}</div>`}
function helperDetails(list=[]){return list.filter(Boolean).map(d=>`<details class="helperDetails"><summary>${esc(d.title)}</summary><div class="helperBody">${d.html}</div></details>`).join('')}
function transcriptHtml(lines){return `<div class="transcriptBox">${lines.map(t=>`<p><b>${esc(t.name)}:</b> ${esc(t.text)}</p>`).join('')}</div>`}
function listHint(items){return `<ul class="hintList">${items.map(t=>`<li>${t}</li>`).join('')}</ul>`}
function helperDock(list=[]){const html=helperDetails(list);return html?`<div class="visualHelpers">${html}</div>`:''}
function visualWithHelpers(visualHTML,helpers=[]){return `<div class="visualWithHelpers"><div class="visualMain">${visualHTML}</div>${helperDock(helpers)}</div>`}

let currentAudio=null,playToken=0,currentUtterance=null;
const ttsAudio=document.createElement('audio');ttsAudio.preload='auto';ttsAudio.setAttribute('playsinline','');ttsAudio.referrerPolicy='no-referrer';ttsAudio.style.display='none';document.body.appendChild(ttsAudio);
function providerUrls(text){const q=encodeURIComponent(text.replace(/\s+/g,' ').trim());return [`https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&tl=en-GB&q=${q}`,`https://translate.google.com/translate_tts?ie=UTF-8&client=gtx&tl=en-GB&q=${q}`,`https://translate.googleapis.com/translate_tts?ie=UTF-8&client=gtx&tl=en-GB&q=${q}`]}
function splitTTS(text,max=180){const clean=text.replace(/\s+/g,' ').trim();if(clean.length<=max)return [clean];const out=[];let rest=clean;while(rest.length){if(rest.length<=max){out.push(rest);break}let cut=rest.lastIndexOf(' ',max);if(cut<70)cut=max;out.push(rest.slice(0,cut).trim());rest=rest.slice(cut).trim()}return out.filter(Boolean)}
function stopAudio(){playToken++;try{ttsAudio.pause();ttsAudio.removeAttribute('src');ttsAudio.load()}catch(e){}try{speechSynthesis.cancel()}catch(e){}currentAudio=null;currentUtterance=null}
function playUrl(url,token){return new Promise((resolve,reject)=>{if(token!==playToken)return reject(new Error('cancelled'));const a=ttsAudio;currentAudio=a;let finished=false;const cleanup=()=>{a.onended=a.onerror=a.onabort=null;clearTimeout(timer)};const timer=setTimeout(()=>{if(finished)return;finished=true;cleanup();reject(new Error('timeout'))},10000);a.onended=()=>{if(finished)return;finished=true;cleanup();resolve()};a.onerror=()=>{if(finished)return;finished=true;cleanup();reject(new Error('audio error'))};a.src=url;a.currentTime=0;a.load();const p=a.play();if(p&&p.catch)p.catch(e=>{if(finished)return;finished=true;cleanup();reject(e)})})}
function speechFallback(text,token){return new Promise((resolve,reject)=>{try{if(token!==playToken)return reject(new Error('cancelled'));const u=new SpeechSynthesisUtterance(text);currentUtterance=u;u.lang='en-GB';u.rate=.9;u.pitch=1;u.onend=resolve;u.onerror=reject;speechSynthesis.speak(u)}catch(e){reject(e)}})}
async function playChunk(text,token){for(const url of providerUrls(text)){try{await playUrl(url,token);return}catch(e){}}await speechFallback(text,token)}
async function playSequence(texts,btn,idle='▶ Прослушать'){if(btn?.classList.contains('busy')){stopAudio();btn.classList.remove('busy');btn.textContent=idle;return}stopAudio();const token=++playToken;if(btn){btn.classList.add('busy');btn.textContent='■'}try{for(const t of texts){if(token!==playToken)return;await playChunk(t,token)}if(token===playToken&&btn){btn.classList.remove('busy');btn.textContent=idle}}catch(e){if(token===playToken&&btn){btn.classList.remove('busy');btn.classList.add('error');btn.textContent='!';setTimeout(()=>{btn.classList.remove('error');btn.textContent=idle},1500)}}}
function playText(text,btn,idle='▶ Прослушать'){return playSequence(splitTTS(text),btn,idle)}
function playScript(lines,btn,label='Диалог'){return playSequence(lines.flatMap(x=>splitTTS(x.text,110)),btn,`▶ ${label}`)}
function audioBtn(id,label='Прослушать',disabled=false){return `<button class="audioBtn" id="${id}" ${disabled?'disabled':''}>▶ ${label}</button><span class="audioMeta">British English · синтез речи</span>`}

function slotFallback(icon,titleTxt,caption){return `<div class="slotFallback"><div><div class="slotIcon">${icon}</div><strong>${esc(titleTxt)}</strong><span>${esc(caption)}</span><small>WOW SCHOOL</small></div></div>`}
function visualSlot(file,icon,badge,caption,alt){return `<div class="visualSlot"><img src="assets/images/${file}" alt="${esc(alt)}" onload="this.parentElement.classList.add('loaded')" onerror="this.style.display='none';this.parentElement.classList.remove('loaded')"><div class="visualBadge">${esc(badge)}</div>${slotFallback(icon,badge,caption)}</div>`}
function heroSlot(){return `<div class="heroSlot"><img class="heroImage" src="assets/images/preview-episode4.jpg" alt="Episode 4 What's the date preview" onload="this.parentElement.classList.add('loaded')" onerror="this.style.display='none';this.parentElement.classList.remove('loaded')">${slotFallback('📅','Episode 4 · What\'s the date?','Months · ordinal numbers · dates · phone English')}</div>`}
function bindGlobalUi(){const dt=document.getElementById('devToggle');if(dt)dt.ondblclick=()=>{devMode=!devMode;render()};if(devMode){document.getElementById('devPrevBlock').onclick=()=>changeBlock(-1);document.getElementById('devNextBlock').onclick=()=>changeBlock(1);document.getElementById('devPrevTask').onclick=()=>changeTask(-1);document.getElementById('devNextTask').onclick=()=>changeTask(1)}}

function start(){app.innerHTML=shell(`<div class="dateHero"><div class="heroCopy"><div class="heroKicker">Practical English · Episode 4</div><h1>What's the <span>date?</span></h1><p>Повтори месяцы и порядковые числительные, потренируй даты и короткие телефонные фразы. Если станет сложно, открывай подсказки рядом с изображением.</p><div class="dateFeatureRow"><span>Month Flip</span><span>Ordinal Lift</span><span>Calendar Tap</span><span>Sentence Builder</span><span>Phone English</span><span>Save the Date</span></div><p class="dateNote">Задания короткие и рассчитаны на уровень Beginner: длинных аудио без текстовой опоры здесь нет.</p><div class="heroBtns"><button class="btn primary" id="begin">Начать →</button><button class="btn secondary" id="reset">Сбросить прогресс</button></div></div><div class="heroVisual">${heroSlot()}</div></div>`);document.getElementById('begin').onclick=()=>{state.screen=1;save();render()};document.getElementById('reset').onclick=()=>{localStorage.removeItem(STORAGE_KEY);state=fresh();render()};bindGlobalUi()}

function months(){const sec='months',idx=state.idx[sec]||0,item=data.months[idx],done=solved(sec,idx),opts=rotateOptions(item.o,idx);const helpers=[{title:'Подсказка',html:listHint(['Смотри на английские названия месяцев на карточках.','Нажми нужную карточку: она перевернётся и покажет перевод.'])}];app.innerHTML=shell(`${title(1,'Month Flip','Выбери английский месяц и переверни карточку')}<div class="blockBody"><div class="visualCard">${visualWithHelpers(visualSlot('block1-month-flip.jpg','🗓️','MONTH FLIP','Months in everyday life','month-themed lifestyle scene'),helpers)}</div><div class="questionCard"><div class="kicker">MONTH FLIP</div><div class="prompt">Find the month.</div><div class="monthFlipWrap"><div class="monthCue">Русское слово: <b>${esc(item.ru)}</b></div><div class="monthFlipGrid">${opts.map((m,i)=>`<button class="monthFlipCard ${done&&m===item.en?'flipped correct':''}" data-month="${esc(m)}" ${done?'disabled':''}><span class="monthFlipInner"><span class="monthFace monthFront"><strong>${esc(m)}</strong><small>tap to flip</small></span><span class="monthFace monthBack"><b>${esc(MONTHS_RU[MONTHS.indexOf(m)])}</b><span>month ${MONTHS.indexOf(m)+1}</span></span></span></button>`).join('')}</div></div><div class="statusWrap"><div id="fb">${done?feedback('good',`Верно — ${item.en}.`):feedback('neutral','Выбери английский месяц.')}</div>${miniProgress(sec,idx,data.months.length)}</div></div></div><div class="footerActions"><div class="leftActions">${audioBtn('monthAudio','Слово',!done)}</div><button class="nextBtn" id="next" ${done?'':'disabled'}>${idx===data.months.length-1?'Следующий блок →':'Следующее задание →'}</button></div>`);
  document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{if(done)return;const ok=b.dataset.month===item.en;b.classList.add('flipped',ok?'correct':'wrong');recordAttempt(sec,idx,ok);if(ok){document.querySelectorAll('[data-month]').forEach(x=>x.disabled=true);document.getElementById('fb').innerHTML=feedback('good',`Верно — ${item.en}.`);document.getElementById('next').disabled=false;const ab=document.getElementById('monthAudio');ab.disabled=false;setTimeout(()=>playText(item.en,ab,'▶ Слово'),250)}else{document.getElementById('fb').innerHTML=feedback('bad','Не этот месяц. Посмотри перевод на обороте и попробуй ещё раз.');setTimeout(()=>b.classList.remove('flipped','wrong'),950)}});
  document.getElementById('monthAudio').onclick=function(){if(!this.disabled)playText(item.en,this,'▶ Слово')};document.getElementById('next').onclick=()=>{if(idx<data.months.length-1){state.idx[sec]=idx+1;save();render()}else{state.screen=2;save();render()}};bindGlobalUi()}

function ordinals(){const sec='ordinals',idx=state.idx[sec]||0,item=data.ordinals[idx],done=solved(sec,idx),opts=rotateOptions(item.o,idx),wordSize=item.word.length>11?17:item.word.length>8?20:24;const helpers=[{title:'Правило',html:listHint(['1 → 1st · 2 → 2nd · 3 → 3rd.','Большинство остальных форм заканчиваются на -th.','Слушай произношение: некоторые формы меняются заметно, например twelve → twelfth.'])}];app.innerHTML=shell(`${title(2,'Ordinal Lift','Подними лифт на правильный ordinal number')}<div class="blockBody"><div class="visualCard">${visualWithHelpers(visualSlot('block2-ordinal-lift.jpg','🔢','ORDINAL LIFT','Ordinal numbers in a modern setting','ordinal-number learning scene'),helpers)}</div><div class="questionCard"><div class="kicker">ORDINAL LIFT</div><div class="prompt">Which ordinal number is “${esc(item.word)}”?</div><div class="subprompt">Выбери правильную запись порядкового числительного.</div><div class="ordinalStage"><div class="liftShaft"><div class="liftDisplay"><div><strong style="font-size:${done?30:wordSize}px">${done?item.a:esc(item.word)}</strong><small>${done?item.word.toUpperCase():'LISTEN · READ · CHOOSE'}</small></div></div><div class="liftTrack"><div class="liftCar" id="liftCar" style="bottom:${done?78:5}%">↟</div></div></div><div class="liftButtons">${opts.map(o=>`<button class="floorBtn ${done&&o===item.a?'correct':''}" data-floor="${esc(o)}" ${done?'disabled':''}>${esc(o)}</button>`).join('')}</div></div><div class="statusWrap"><div id="fb">${done?feedback('good',`${item.word} → ${item.a}`):feedback('neutral','Прочитай или прослушай слово и выбери его запись.')}</div>${miniProgress(sec,idx,data.ordinals.length)}</div></div></div><div class="footerActions"><div class="leftActions">${audioBtn('ordAudio','Произношение')}</div><button class="nextBtn" id="next" ${done?'':'disabled'}>${idx===data.ordinals.length-1?'Следующий блок →':'Следующее задание →'}</button></div>`);
  document.getElementById('ordAudio').onclick=function(){playText(item.word,this,'▶ Произношение')};document.querySelectorAll('[data-floor]').forEach(b=>b.onclick=()=>{if(done)return;const ok=b.dataset.floor===item.a;recordAttempt(sec,idx,ok);if(ok){b.classList.add('correct');document.querySelectorAll('[data-floor]').forEach(x=>x.disabled=true);document.getElementById('liftCar').style.bottom='78%';const liftStrong=document.querySelector('.liftDisplay strong');liftStrong.textContent=item.a;liftStrong.style.fontSize='30px';document.querySelector('.liftDisplay small').textContent=item.word.toUpperCase();document.getElementById('fb').innerHTML=feedback('good',`${item.word} → ${item.a}`);document.getElementById('next').disabled=false;playText(item.word,null,'')}else{b.classList.add('wrongFlash');document.getElementById('fb').innerHTML=feedback('bad','Попробуй ещё раз.');setTimeout(()=>b.classList.remove('wrongFlash'),420)}});document.getElementById('next').onclick=()=>{if(idx<data.ordinals.length-1){state.idx[sec]=idx+1;save();render()}else{state.screen=3;save();render()}};bindGlobalUi()}

function matchDates(){const sec='match',round=state.matchRound||0,pairs=data.match[round],found=state.matchFound[round]||[],rightOrder=rotateOptions(pairs.map(p=>p.written),round+2);const allDone=found.length===pairs.length;const helpers=[{title:'Подсказка',html:listHint(['Слева — дата словами, справа — та же дата в письменном виде.','Сначала выбери фразу слева, затем соответствующую дату справа.','Верная пара соединится анимированной линией.'])}];app.innerHTML=shell(`${title(3,'Date Match','Соедини произнесённую и написанную дату')}<div class="blockBody"><div class="visualCard">${visualWithHelpers(visualSlot('block3-date-match.jpg','🔗','DATE MATCH','Connect two versions of the same date','people matching date cards'),helpers)}</div><div class="questionCard"><div class="kicker">DATE MATCH · ROUND ${round+1}/2</div><div class="prompt">Connect all 4 pairs.</div><div class="matchLineBoard" id="matchBoard"><svg class="matchSvg" id="matchSvg"></svg><div class="matchLineCol">${pairs.map((p,i)=>`<button class="matchLineBtn ${found.includes(i)?'done':''} ${state.matchLeft===i?'active':''}" data-left="${i}" ${found.includes(i)?'disabled':''}>${esc(p.spoken)}</button>`).join('')}</div><div class="matchLineCol">${rightOrder.map(w=>{const pi=pairs.findIndex(p=>p.written===w);return `<button class="matchLineBtn ${found.includes(pi)?'done':''}" data-right="${pi}" ${found.includes(pi)?'disabled':''}>${esc(w)}</button>`}).join('')}</div></div><div class="roundPills"><span class="${round===0?'on':''}">Раунд 1</span><span class="${round===1?'on':''}">Раунд 2</span></div><div class="statusWrap"><div id="fb">${allDone?feedback('good','Все пары соединены!'):feedback('neutral','Выбери фразу слева.')}</div><div class="internalProgress"><div class="miniDots">${Array.from({length:4},(_,i)=>`<i class="miniDot ${i<found.length?'done':i===found.length?'current':''}"></i>`).join('')}</div><div class="counter">Найдено ${found.length} из 4</div></div></div></div></div><div class="footerActions"><div class="leftActions">${audioBtn('matchAudio','Фразы')}</div><button class="nextBtn" id="next" ${allDone?'':'disabled'}>${round===1?'Следующий блок →':'Следующий раунд →'}</button></div>`);
  function drawLines(){const board=document.getElementById('matchBoard'),svg=document.getElementById('matchSvg');if(!board||!svg)return;svg.innerHTML='';const br=board.getBoundingClientRect(),localW=board.clientWidth,localH=board.clientHeight,sx=br.width?localW/br.width:1,sy=br.height?localH/br.height:1;svg.setAttribute('viewBox',`0 0 ${localW} ${localH}`);svg.setAttribute('preserveAspectRatio','none');found.forEach(i=>{const a=board.querySelector(`[data-left="${i}"]`),b=board.querySelector(`[data-right="${i}"]`);if(!a||!b)return;const ar=a.getBoundingClientRect(),rr=b.getBoundingClientRect();const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',(ar.right-br.left)*sx);line.setAttribute('y1',(ar.top+ar.height/2-br.top)*sy);line.setAttribute('x2',(rr.left-br.left)*sx);line.setAttribute('y2',(rr.top+rr.height/2-br.top)*sy);svg.appendChild(line)})}
  requestAnimationFrame(drawLines);document.getElementById('matchAudio').onclick=function(){playSequence(pairs.map(p=>p.spoken),this,'▶ Фразы')};document.querySelectorAll('[data-left]').forEach(b=>b.onclick=()=>{if(b.disabled)return;state.matchLeft=+b.dataset.left;save();document.querySelectorAll('[data-left]').forEach(x=>x.classList.toggle('active',+x.dataset.left===state.matchLeft));document.getElementById('fb').innerHTML=feedback('neutral','Теперь выбери ту же дату справа.')});document.querySelectorAll('[data-right]').forEach(b=>b.onclick=()=>{if(b.disabled)return;if(state.matchLeft===null||state.matchLeft===undefined){document.getElementById('fb').innerHTML=feedback('bad','Сначала выбери фразу слева.');return}const left=state.matchLeft,ok=left===+b.dataset.right;recordAttempt(sec,round*4+left,ok);if(ok){if(!found.includes(left))found.push(left);state.matchFound[round]=found;state.matchLeft=null;save();render()}else{b.classList.add('wrongFlash');document.getElementById('fb').innerHTML=feedback('bad','Это другая дата. Попробуй ещё раз.');setTimeout(()=>b.classList.remove('wrongFlash'),420)}});document.getElementById('next').onclick=()=>{if(round===0){state.matchRound=1;state.matchLeft=null;save();render()}else{state.screen=4;save();render()}};bindGlobalUi()}

function calendarTap(){const sec='calendar',idx=state.idx[sec]||0,item=data.calendar[idx],done=solved(sec,idx),monthIndex=MONTHS.indexOf(item.month);const helpers=[{title:'Подсказка',html:listHint(['Сначала найди месяц в заголовке календаря.','Потом нажми число, которое ты услышал или прочитал.'])}];const first=(new Date(2026,monthIndex,1).getDay()+6)%7,days=new Date(2026,monthIndex+1,0).getDate();let cells='';for(let i=0;i<42;i++){const d=i-first+1;cells+=d>=1&&d<=days?`<button class="dayCell ${done&&d===item.day?'correct':''}" data-day="${d}" ${done?'disabled':''}>${d}</button>`:`<span class="dayCell blank"></span>`}
  app.innerHTML=shell(`${title(4,'Calendar Tap','Найди услышанную дату на календаре')}<div class="blockBody"><div class="visualCard">${visualWithHelpers(visualSlot('block4-calendar-tap.jpg','📆','CALENDAR TAP','Find the date visually','calendar planning scene'),helpers)}</div><div class="questionCard"><div class="kicker">CALENDAR TAP</div><div class="prompt">Find ${esc(datePhrase(item.day,item.month))}.</div><div class="calendarWrap"><div class="calendarHead"><strong>${esc(item.month)}</strong><span>tap the day</span></div><div class="calendarGrid">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<span class="weekday">${x}</span>`).join('')}${cells}</div></div><div class="statusWrap"><div id="fb">${done?feedback('good',`Верно — ${item.day}${suffix(item.day)} ${item.month}.`):feedback('neutral','Нажми нужный день.')}</div>${miniProgress(sec,idx,data.calendar.length)}</div></div></div><div class="footerActions"><div class="leftActions">${audioBtn('calAudio','Дату')}</div><button class="nextBtn" id="next" ${done?'':'disabled'}>${idx===data.calendar.length-1?'Следующий блок →':'Следующее задание →'}</button></div>`);
  document.getElementById('calAudio').onclick=function(){playText(datePhrase(item.day,item.month),this,'▶ Дату')};document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{if(done)return;const ok=+b.dataset.day===item.day;recordAttempt(sec,idx,ok);if(ok){b.classList.add('correct');document.querySelectorAll('[data-day]').forEach(x=>x.disabled=true);document.getElementById('fb').innerHTML=feedback('good',`Верно — ${item.day}${suffix(item.day)} ${item.month}.`);document.getElementById('next').disabled=false}else{b.classList.add('wrongFlash');document.getElementById('fb').innerHTML=feedback('bad','Проверь число и попробуй ещё раз.');setTimeout(()=>b.classList.remove('wrongFlash'),420)}});document.getElementById('next').onclick=()=>{if(idx<data.calendar.length-1){state.idx[sec]=idx+1;save();render()}else{state.screen=5;save();render()}};bindGlobalUi()}

function shuffledTokens(arr,seed){const out=arr.map((t,i)=>({t,i}));for(let i=out.length-1;i>0;i--){const j=(seed*5+i*3+1)%(i+1);[out[i],out[j]]=[out[j],out[i]]}return out}
function builder(){const sec='builder',idx=state.idx[sec]||0,item=data.builder[idx],done=solved(sec,idx);if(!Array.isArray(state.builderChosen))state.builderChosen=[];const bank=shuffledTokens(item.tokens,idx+2);const helpers=[{title:'Подсказка',html:listHint(['Начни с вопросительного слова или подлежащего.','В вопросе “What’s the date today?” слово today стоит в конце.','Можно прослушать модель, если нужна опора.'])}];app.innerHTML=shell(`${title(5,'Sentence Builder','Собери фразу из слов')}<div class="blockBody"><div class="visualCard">${visualWithHelpers(visualSlot('block5-builder.jpg','🧩','SENTENCE BUILDER','Build a useful date phrase','date cards arranged into a phrase'),helpers)}</div><div class="questionCard dateBuilder"><div class="kicker">SENTENCE BUILDER</div><div class="prompt">Build the sentence.</div><div class="builderWrap"><div class="builderCue">${esc(item.ru)}</div><div class="builderResult" id="builderResult">${state.builderChosen.length?state.builderChosen.map((x,i)=>`<button class="token answerToken" data-remove="${i}">${esc(x.t)}</button>`).join(''):`<span class="builderPlaceholder">Нажимай слова в правильном порядке.</span>`}</div><div class="tokenBank">${bank.map(x=>`<button class="token ${state.builderChosen.some(c=>c.i===x.i)?'used':''}" data-token="${x.i}">${esc(x.t)}</button>`).join('')}</div><div class="builderActions"><button class="smallBtn" id="clear">Очистить</button><button class="smallBtn primary" id="check">Проверить</button></div></div><div class="statusWrap"><div id="fb">${done?feedback('good','Верно! Послушай модель и повтори вслух.'):feedback('neutral','Собери предложение.')}</div>${miniProgress(sec,idx,data.builder.length)}</div></div></div><div class="footerActions"><div class="leftActions">${audioBtn('builderAudio','Модель')}</div><button class="nextBtn" id="next" ${done?'':'disabled'}>${idx===data.builder.length-1?'Следующий блок →':'Следующее задание →'}</button></div>`);
  document.getElementById('builderAudio').onclick=function(){playText(item.a,this,'▶ Модель')};document.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{const ti=+b.dataset.token;if(state.builderChosen.some(c=>c.i===ti))return;state.builderChosen.push({i:ti,t:item.tokens[ti]});save();render()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.builderChosen.splice(+b.dataset.remove,1);save();render()});document.getElementById('clear').onclick=()=>{state.builderChosen=[];save();render()};document.getElementById('check').onclick=()=>{if(done)return;const built=state.builderChosen.map(x=>x.t).join(' '),ok=built===item.a;recordAttempt(sec,idx,ok);if(ok){document.getElementById('fb').innerHTML=feedback('good','Верно! Послушай модель и повтори вслух.');document.getElementById('next').disabled=false;playText(item.a,null,'')}else{document.getElementById('fb').innerHTML=feedback('bad','Порядок пока неверный. Попробуй переставить слова.')}};document.getElementById('next').onclick=()=>{state.builderChosen=[];if(idx<data.builder.length-1){state.idx[sec]=idx+1;save();render()}else{state.screen=6;save();render()}};bindGlobalUi()}

function phone(){const sec='phone',idx=state.idx[sec]||0,item=data.phone[idx],done=solved(sec,idx),opts=rotateOptions(item.o,idx);const helpers=[{title:'Открыть текст диалога',html:transcriptHtml(item.lines)},{title:'Подсказка',html:listHint(['Сначала послушай короткий диалог.','Если не всё понятно на слух, открой текст.','Имена видны в тексте, но в аудио произносятся только реплики.'])}];app.innerHTML=shell(`${title(6,'Phone English','Послушай короткий звонок и ответь')}<div class="blockBody"><div class="visualCard">${visualWithHelpers(visualSlot('block6-phone.jpg','📱','PHONE ENGLISH','A short practical phone conversation','portrait phone conversation scene'),helpers)}</div><div class="questionCard"><div class="kicker">PHONE ENGLISH</div><div class="prompt">${esc(item.q)}</div><div class="phonePanel"><div class="phoneBubble"><div class="phoneIcon">☎</div><div><strong>${esc(item.caller)} · incoming call</strong><span>Короткий диалог · можно открыть transcript</span></div></div><div class="phoneAnswers">${opts.map(o=>`<button class="answer ${done&&o===item.a?'correct':''}" data-answer="${esc(o)}" ${done?'disabled':''}>${esc(o)}</button>`).join('')}</div></div><div class="statusWrap"><div id="fb">${done?feedback('good','Верно!'):feedback('neutral','Послушай и выбери ответ.')}</div>${miniProgress(sec,idx,data.phone.length)}</div></div></div><div class="footerActions"><div class="leftActions">${audioBtn('phoneAudio','Диалог')}</div><button class="nextBtn" id="next" ${done?'':'disabled'}>${idx===data.phone.length-1?'Следующий блок →':'Следующее задание →'}</button></div>`);
  document.getElementById('phoneAudio').onclick=function(){playScript(item.lines,this,'Диалог')};document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(done)return;const ok=b.dataset.answer===item.a;recordAttempt(sec,idx,ok);if(ok){b.classList.add('correct');document.querySelectorAll('[data-answer]').forEach(x=>x.disabled=true);document.getElementById('fb').innerHTML=feedback('good','Верно!');document.getElementById('next').disabled=false}else{b.classList.add('wrongFlash');document.getElementById('fb').innerHTML=feedback('bad','Не совсем. Открой текст диалога, если нужна опора.');setTimeout(()=>b.classList.remove('wrongFlash'),420)}});document.getElementById('next').onclick=()=>{if(idx<data.phone.length-1){state.idx[sec]=idx+1;save();render()}else{state.screen=7;save();render()}};bindGlobalUi()}

function stamp(){const sec='stamp',idx=state.idx[sec]||0,item=data.stamp[idx],done=solved(sec,idx),opts=rotateOptions(item.o,idx);const helpers=[{title:'Правило',html:listHint(['В речи: the fifth of May.','На письме: 5th May.','Смотри внимательно на окончание: st / nd / rd / th.'])}];app.innerHTML=shell(`${title(7,'Date Stamp','Выбери ту же дату в другом формате')}<div class="blockBody"><div class="visualCard">${visualWithHelpers(visualSlot('block7-date-stamp.jpg','🎟️','DATE STAMP','Dates on invitations and tickets','event ticket and calendar scene'),helpers)}</div><div class="questionCard"><div class="kicker">DATE STAMP</div><div class="prompt">Stamp the matching date.</div><div class="ticketWrap"><div class="eventTicket ${done?'stamped':''}" id="eventTicket"><span class="eventType">${esc(item.event)}</span><h3>${esc(item.cue)}</h3><p>Find the same date.</p><div class="stampMark">MATCHED ✓</div></div><div class="stampChoices">${opts.map(o=>`<button class="stampBtn ${done&&o===item.a?'correct':''}" data-stamp="${esc(o)}" ${done?'disabled':''}>${esc(o)}</button>`).join('')}</div><div></div></div><div class="statusWrap"><div id="fb">${done?feedback('good','Верно — штамп поставлен.'):feedback('neutral','Выбери эквивалентную дату.')}</div>${miniProgress(sec,idx,data.stamp.length)}</div></div></div><div class="footerActions"><div class="leftActions">${audioBtn('stampAudio','Дату')}</div><button class="nextBtn" id="next" ${done?'':'disabled'}>${idx===data.stamp.length-1?'Следующий блок →':'Следующее задание →'}</button></div>`);
  document.getElementById('stampAudio').onclick=function(){playText(item.audio,this,'▶ Дату')};document.querySelectorAll('[data-stamp]').forEach(b=>b.onclick=()=>{if(done)return;const ok=b.dataset.stamp===item.a;recordAttempt(sec,idx,ok);if(ok){b.classList.add('correct');document.querySelectorAll('[data-stamp]').forEach(x=>x.disabled=true);document.getElementById('eventTicket').classList.add('stamped');document.getElementById('fb').innerHTML=feedback('good','Верно — штамп поставлен.');document.getElementById('next').disabled=false}else{b.classList.add('wrongFlash');document.getElementById('fb').innerHTML=feedback('bad','Сравни число, месяц и окончание ordinal number.');setTimeout(()=>b.classList.remove('wrongFlash'),420)}});document.getElementById('next').onclick=()=>{if(idx<data.stamp.length-1){state.idx[sec]=idx+1;save();render()}else{state.screen=8;save();render()}};bindGlobalUi()}

function ensurePicker(idx,item){if(!state.picker[idx])state.picker[idx]={m:(item.month+10)%12,d:item.day===1?2:item.day-1};return state.picker[idx]}
function saveDate(){const sec='save',idx=state.idx[sec]||0,item=data.save[idx],pick=ensurePicker(idx,item),done=solved(sec,idx);const helpers=[{title:'Перевод фразы',html:`<div class="transcriptBox"><p>${esc(item.ru)}</p></div>`},{title:'Подсказка',html:listHint(['Сначала выставь месяц.','Потом выставь число.','Нажми Save date, когда всё готово.'])}];const prev=MONTHS[(pick.m+11)%12],next=MONTHS[(pick.m+1)%12];app.innerHTML=shell(`${title(8,'Save the Date','Настрой месяц и число и сохрани дату')}<div class="blockBody"><div class="visualCard">${visualWithHelpers(visualSlot('block8-save-date.jpg','✨','SAVE THE DATE','Set the date from a short message','modern calendar planning scene'),helpers)}</div><div class="questionCard saveDateCard ${done?'saved':''}"><div class="kicker">SAVE THE DATE · ${esc(item.person)}</div><div class="prompt">Set the date.</div><div class="saveWrap"><div class="voiceNote"><div class="voiceWave"><i></i><i></i><i></i><i></i><i></i></div><div class="voiceText">${esc(item.text)}</div></div><div class="datePicker"><div class="monthWheel"><div class="wheelLabel">Month</div><div class="monthCarousel"><button class="wheelBtn" id="monthPrev" ${done?'disabled':''}>‹</button><div class="monthCurrent"><div><strong>${esc(MONTHS[pick.m])}</strong><small>${esc(prev)} · ${esc(next)}</small></div></div><button class="wheelBtn" id="monthNext" ${done?'disabled':''}>›</button></div></div><div class="dayWheel"><div class="wheelLabel">Day</div><div class="daySheet"><strong>${pick.d}</strong></div><div class="dayControls"><button class="wheelBtn" id="dayMinus" ${done?'disabled':''}>−</button><button class="wheelBtn" id="dayPlus" ${done?'disabled':''}>+</button></div></div></div><div class="saveAction"><button class="saveBtn" id="saveBtn" ${done?'disabled':''}>${done?'Saved ✓':'Save date'}</button></div></div><div class="statusWrap"><div id="fb">${done?feedback('good',`Сохранено: ${item.day}${suffix(item.day)} ${MONTHS[item.month]}.`):feedback('neutral','Настрой дату и нажми Save date.')}</div>${miniProgress(sec,idx,data.save.length)}</div></div></div><div class="footerActions"><div class="leftActions">${audioBtn('saveAudio','Фразу')}</div><button class="nextBtn" id="next" ${done?'':'disabled'}>${idx===data.save.length-1?'Результаты →':'Следующая дата →'}</button></div>`);
  const update=(m,d)=>{pick.m=(m+12)%12;pick.d=Math.max(1,Math.min(31,d));state.picker[idx]=pick;save();render()};document.getElementById('saveAudio').onclick=function(){playText(item.text,this,'▶ Фразу')};if(!done){document.getElementById('monthPrev').onclick=()=>update(pick.m-1,pick.d);document.getElementById('monthNext').onclick=()=>update(pick.m+1,pick.d);document.getElementById('dayMinus').onclick=()=>update(pick.m,pick.d-1);document.getElementById('dayPlus').onclick=()=>update(pick.m,pick.d+1);document.getElementById('saveBtn').onclick=()=>{const ok=pick.m===item.month&&pick.d===item.day;recordAttempt(sec,idx,ok);if(ok){document.getElementById('fb').innerHTML=feedback('good',`Сохранено: ${item.day}${suffix(item.day)} ${MONTHS[item.month]}.`);document.getElementById('next').disabled=false;document.querySelector('.saveDateCard').classList.add('saved');document.getElementById('saveBtn').textContent='Saved ✓';document.getElementById('saveBtn').disabled=true;['monthPrev','monthNext','dayMinus','dayPlus'].forEach(id=>document.getElementById(id).disabled=true)}else{document.getElementById('fb').innerHTML=feedback('bad','Дата пока не совпадает с фразой. Проверь месяц и число.')}}}document.getElementById('next').onclick=()=>{if(idx<data.save.length-1){state.idx[sec]=idx+1;save();render()}else{state.screen=9;save();render()}};bindGlobalUi()}

function results(){const totalMax=SECTIONS.reduce((n,k)=>n+MAX[k],0),total=SECTIONS.reduce((n,k)=>n+score(k),0),pct=Math.round(total/totalMax*100),sorted=[...SECTIONS].sort((a,b)=>score(b)/MAX[b]-score(a)/MAX[a]),best=sorted[0],weak=sorted.at(-1);app.innerHTML=shell(`<div class="titlebar"><div class="titlewrap"><h1>Your <span class="n">Results</span></h1><p>Beginner · Episode 4 · What's the date?</p></div><div class="progressBox"><strong>Готово</strong><div class="track"><i style="width:100%"></i></div></div></div><div class="results"><div class="ring" style="--pct:${pct}"><strong>${pct}%</strong><span>с первого раза</span></div><div><div class="resultList">${SECTIONS.map(k=>{const p=Math.round(score(k)/MAX[k]*100);return `<div class="resrow"><label>${LABELS[k]}</label><div class="resbar"><i style="width:${p}%"></i></div><b>${score(k)}/${MAX[k]}</b></div>`}).join('')}</div><div class="coach"><div><strong>Сильнее всего</strong><p>${LABELS[best]} — здесь было больше всего ответов с первой попытки.</p></div><div><strong>Можно повторить</strong><p>${LABELS[weak]} — пройди этот блок ещё раз для уверенности.</p></div></div><div class="coach" style="margin-top:14px"><div><strong>Ты потренировал(а)</strong><p>Months, ordinal numbers, saying the date и короткие телефонные фразы.</p></div><div><strong>Финальная практика</strong><p>Назови сегодняшнюю дату и три важные даты для тебя по-английски.</p></div></div><div class="heroBtns" style="margin-top:16px"><button class="btn primary" id="retry">Пройти ещё раз</button><button class="btn secondary" id="home">На главную</button></div></div></div>`);document.getElementById('retry').onclick=()=>{state=fresh();state.screen=1;save();render()};document.getElementById('home').onclick=()=>{state.screen=0;save();render()};bindGlobalUi()}

function render(){stopAudio();({0:start,1:months,2:ordinals,3:matchDates,4:calendarTap,5:builder,6:phone,7:stamp,8:saveDate,9:results}[state.screen]||start)()}
render();
